#!/bin/bash

## Build
mvn package -Pprod -DskipTests

## Create expected directories
mkdir -p $NUCLEAUS_SCAN_TARGET_DIR
mkdir -p $NUCLEAUS_SCAN_LIBRARY_DIR

## Move compiled targets to appropriate directory
mv target/OMIS3.war $NUCLEAUS_SCAN_TARGET_DIR
mv target/OMIS3/WEB-INF/lib/*.jar $NUCLEAUS_SCAN_LIBRARY_DIR
